### ISSUE TITLE
Support modern microprofile annotations

### ISSUE THREAD

**Issue by languitar** [lorislab/mp-rest-client-maven-plugin#1]
When trying to use this project inside Quarkus, the currently generated annotations from `io.swagger.v3.oas.annotations.*` are not compatible with the microprofile implementation supported by Quarkus using the official namespaces.

I am not entirely sure how they can actually end up in the project because the mustache templates in the repo do contain the correct annotations, but for instance, this schema:
```yaml
    Supplier:
      type: object
      properties:
        uuid:
          type: string
      required:
        - uuid
      description: A supplier representation
```
currently results in the following Java code:
```java
package one.plan.rest.models;

import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * A supplier representation
 **/
import java.util.Objects;

    import javax.json.bind.annotation.JsonbProperty;


public class Supplier   {


  @JsonbProperty("uuid")
  public @Valid String uuid = null;




}
```
The Google source code formatter then already dies due to the missing import.
